---
image: voegelas/debian-devel

test:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  script:
    - cpanm --quiet --notest --installdeps .
    - perl Makefile.PL
    - cover -test
